'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Shifts

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelOpenShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelOpenShift As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtOpeningBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpeningBalance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOpenShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenShift As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelCloseShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelCloseShift As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litCashierName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litCashierName As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOpeningTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOpeningTime As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litOpeningBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litOpeningBalance As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''txtClosingBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosingBalance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCloseShift control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseShift As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelReport As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''litReportOpening control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportOpening As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReportCashSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportCashSales As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReportExpected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportExpected As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReportActual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportActual As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''rowDifference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rowDifference As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''litReportDifference control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportDifference As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReportCardSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportCardSales As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''litReportCreditSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litReportCreditSales As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btnPrintReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrintReport As Global.System.Web.UI.WebControls.Button
End Class
